#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define BENOS_TOTAL_INTERRUPTS 512

// 100MB heap size
#define BENOS_HEAP_SIZE_BYTES 104857600
#define BENOS_HEAP_BLOCK_SIZE 4096
#define BENOS_HEAD_ADDRESS 0x01000000
#define BENOS_HEAP_TABLE_ADDRESS 0x00007E00

#define BENOS_SECTOR_SIZE 512

#define BENOS_MAX_FILESYSTEMS 12
#define BENOS_MAX_FILE_DESCRIPTORS 512

#define BENOS_MAX_PATH 108

#define BENOS_TOTAL_GDT_SEGMENTS 6

#define BENOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
// all tasks share the same stack (its ok because they still have different page directories which point to different physical addresses)
#define BENOS_USER_PROGRAM_STACK_SIZE 1024 * 16
#define BENOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define BENOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END BENOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - BENOS_USER_PROGRAM_STACK_SIZE

#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1B

#define BENOS_MAX_PROGRAM_ALLOCATIONS 1024

#define BENOS_MAX_PROCESSES 12

#define BENOS_MAX_ISR80H_COMMANDS 1024

#endif